version: '3.9'
services:
  talk-with-gemini:
    image: xiangfa/talk-with-gemini
    container_name: talk-with-gemini
    environment:
      - ACCESS_PASSWORD=$ACCESS_PASSWORD
      - GEMINI_API_KEY=$GEMINI_API_KEY
      - GEMINI_API_BASE_URL=$GEMINI_API_BASE_URL
      - NEXT_PUBLIC_GEMINI_MODEL_LIST=$NEXT_PUBLIC_GEMINI_MODEL_LIST
      - NEXT_PUBLIC_UPLOAD_LIMIT=$NEXT_PUBLIC_UPLOAD_LIMIT
      - HEAD_SCRIPTS=$HEAD_SCRIPTS
    ports:
      - 5481:3000
